# Generated by Django 5.1.5 on 2025-01-31 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_group', '0003_alter_templategroup_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templategroup',
            old_name='user_id',
            new_name='user',
        ),
    ]
