# Generated by Django 5.1.5 on 2025-01-30 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template_directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('uuid', models.CharField(default=uuid.UUID('762e6be8-8389-457f-b604-b0d43ba77501'), max_length=36, unique=True)),
                ('content', models.TextField()),
                ('template_directory_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='template_directory.templatedirectory')),
            ],
            options={
                'db_table': 'template_file',
            },
        ),
    ]
