# Generated by Django 5.1.5 on 2025-01-30 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('fae57ae4-1c0d-41ad-8823-714d6e143544'), max_length=36, unique=True),
        ),
    ]
