# Generated by Django 5.1.5 on 2025-01-31 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_file', '0003_alter_templatefile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatefile',
            old_name='template_directory_id',
            new_name='template_directory',
        ),
    ]
