# Generated by Django 5.1.5 on 2025-01-30 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(default=uuid.UUID('72b02f23-c128-41e0-ae82-d8f3867dd24b'), max_length=36, unique=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_directory.templatedirectory')),
                ('template_group_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='template_group.templategroup')),
            ],
            options={
                'db_table': 'template_directory',
            },
        ),
    ]
