# Generated by Django 5.1.5 on 2025-01-30 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedirectory',
            name='uuid',
            field=models.CharField(default=uuid.UUID('182e296e-db3d-4f39-ba48-bd5088ab2f78'), max_length=36, unique=True),
        ),
    ]
