# Generated by Django 5.1.5 on 2025-01-31 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_directory', '0003_alter_templatedirectory_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatedirectory',
            old_name='parent_id',
            new_name='parent_directory',
        ),
        migrations.RenameField(
            model_name='templatedirectory',
            old_name='template_group_id',
            new_name='template_group',
        ),
    ]
